### GET all tasks

GET http://localhost:3200/tasks
Content-Type: application/json

### POST a new task

POST http://localhost:3200/tasks
Content-Type: application/json

{
  "title": "Task 1",
  "date": "2020-01-01",
  "description": "Description 1",
  "priority": "high",
  "status": "todo"
}

### Update a task

PUT http://localhost:3200/tasks
Content-Type: application/json

{
  "id": "f9af14a1-5b1c-4e1e-b38c-d59949f8cf89",
  "priority": "medium",
  "status": "inProgress"
}

### Delete a task

DELETE http://localhost:3200/tasks
Content-Type: application/json

{
  "id": "29b92f80-5869-4d4c-9d39-f4aee9bca98f"
}
